---

version: '3.4'

services:
  postgres:
    image: postgres:16.2-bookworm
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: wogdb
    ports:
      - 5432:5432
    volumes:
      - ${PWD}/data:/var/lib/postgresql/data

...