name: World of Games 1312 CI/CD workflow
run-name: ${{ github.actor }} started World of Games 1312 CI/CD workflow 🚀
on: [push]
jobs:
  Build-and-Test-World-of-Games1312:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out repository code"
        uses: actions/checkout@v4

      - name: "Build App images and run on port 8777"
        run: |
          ls ${{ github.workspace }}
          docker-compose build
          docker compose up -d

      - name: "Setup Testing Environment"
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install -r tests/requirements.txt
      
      - name: "Run End 2 End tests"
        run: |
          source .venv/bin/activate
          python3 tests/e2e.py
  